import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import {  Container } from '@chakra-ui/react'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "./providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
    
      <Providers>
      <Container maxW='7xl'>
      <Navbar/>
     {children}
     <Footer/>
      </Container>
      </Providers>
     
   
    
        
      </body>
    </html>
  );
}
